### ISSUE TITLE
out-of-distribution examples link broken

### ISSUE THREAD

**Issue by yangarbiter** [davidstutz/confidence-calibrated-adversarial-training#2]
Hi,

In the README, under the feature section, there is a link to out-of-distribution examples and it links to the following address:
https://github.com/davidstutz/confidence-calibrated-adversarial-training/blob/master/common/eval/out_of_distribution_evaluation.py

But it seems that this file does not exist.
Does this part of experiment made into the paper?

Thanks.

**Comment by davidstutz** [comment]
Thanks for the info. No, the out of distribution evaluation did not make it into the paper, so I did not commit that part. Must have missed it in the feature list. In case you are interested in the confidence-thresholded OOD evaluation, please contact me via email and I will look for it.
